# Generated by Django 3.0.3 on 2020-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_auto_20200425_1922'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cumulativeattendance',
            name='Unique Student Registration in Course',
        ),
        migrations.RenameField(
            model_name='classevent',
            old_name='attendance_taken_by',
            new_name='attendance_taker',
        ),
        migrations.RemoveField(
            model_name='cumulativeattendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cumulativeattendance',
            name='total_lectures',
        ),
        migrations.RemoveField(
            model_name='cumulativeattendance',
            name='total_practicals',
        ),
        migrations.RemoveField(
            model_name='cumulativeattendance',
            name='total_tutorials',
        ),
        migrations.AddField(
            model_name='course',
            name='acad_year_end',
            field=models.IntegerField(default=2021, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='acad_year_start',
            field=models.IntegerField(default=2020, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='total_lectures_held',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='total_practicals_held',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='total_tutorials_held',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
